apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: default
spec:
  clusterIP: 10.96.0.10
  selector:
    app: minio
  ports:
    - port: 9090
      name: console
    - port: 9000
      name: s3
  type: ClusterIP
